import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import * as React from 'react';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import { Grid } from '@mui/material';
import Box from '@mui/material/Box';
import Link from 'next/link'
import bannerImg from '../public/banner.png';
import recent1 from '../public/recent1.png';
import recent2 from '../public/recent2.png';
import recent3 from '../public/recent3.png';
import insights1 from '../public/insights1.png';
import insights2 from '../public/insights2.png';
import insights3 from '../public/insights3.png';
import insights4 from '../public/insights4.png';
import feedback from '../public/feedback.png';
import testimonial from '../public/testimonial.png';
import award1 from '../public/award1.png';
import award2 from '../public/award2.png';
import award3 from '../public/award3.png';
import award4 from '../public/award4.png';
import footerBg from '../public/footer-bg.png';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 
      <div className={styles.header_top}>For Emergency assistance and after hours support +64 21 642 199</div>                
      <div className={styles.header}>
      <div className={styles.logo}>
          <Image
              src="/logo.png"
              alt="banner"
              fill
            />
      </div>
      <div className={styles.menu}>
        <ul>
          <li><Link href='#'> About us</Link></li>
          <li><Link href='#'> Services</Link></li>
          <li><Link href='#'> Property owners</Link></li>
          <li><Link href='#'> Tenant</Link></li>
          <li><Link href='#'> Metronz  insights</Link></li>
          <li><Button variant="contained" className={styles.loginBtn}><Link href='/login'> <span className={styles.mr6}>Login  </span ></Link> | <Link href='#'> <span  className={styles.ml6}> Signup</span></Link></Button></li>
       
        </ul>
        
      </div>
      </div>
     
      <div className={styles.banner}>
        <div className={styles.banner_content}>
          <h3>Our Mission</h3>
          <h5>
             Helping Homeowners and Tenants to achieve harmony through our expertise and skills
          </h5>
          <p>
            Metro NZ is one of top Auckland property management companies. All of our staff are property investors who have expert knowledge of property market and your best interest in mind at all times. Check out our tailored Service we offer as an Auckland property management company.
          </p>
          
            <Button className={styles.banner_btn} variant="contained">Get in Touch with us Today</Button>
         
        </div>
        <div className={styles.banner_img}>
            <Image
                src={bannerImg}
                alt="banner"
                fill
                priority
              />
          </div> 
      </div>
       
      <div className={styles.fullwithContent}>
        <div className={styles.pageTitleLeft}>Recent Listings</div> 
        <div className={styles.recentListingsImg}>
          
          <Box sx={{ flexGrow: 1, mt: 4 }}>
            <Grid container spacing={4}>
                <Grid item xs={4}>
                  <div className={styles.recentImg}>
                      <Image
                        src={recent1}
                        alt="banner"
                        fill
                        priority
                      />
                  </div>
                </Grid>
                <Grid item xs={4}>
                  <div className={styles.recentImg}>
                      <Image
                        src={recent2}
                        alt="banner"
                        fill
                        priority
                      />
                  </div>
                </Grid>
                <Grid item xs={4}>
                  <div className={styles.recentImg}>
                      <Image
                        src={recent3}
                        alt="banner"
                        fill
                        priority
                      />
                  </div>
                </Grid>
                
            </Grid>
          </Box>
          
          <div className={styles.viewMoreBtnwrap}>
             <Button className={styles.viewMore} variant="contained">View More Listing</Button>
          </div>

          <div className={styles.pageTitleCenter}>Metronz Insights</div>

        </div> 

        <Box sx={{ flexGrow: 1, mt: 4 }}>
            <Grid container spacing={4}>
                <Grid item xs={3}>
                  <div className={styles.metronzImgWrap}>
                    <div className={styles.metronzImg}>
                        <Image
                          src={insights1}
                          alt="banner"
                          fill
                          priority
                        />
                      </div>
                      <div className={styles.metronzTitle}>Healthy Home Standards </div>
                  </div>
                </Grid>

                <Grid item xs={3}>
                  <div className={styles.metronzImgWrap}>
                    <div className={styles.metronzImg}>
                        <Image
                          src={insights2}
                          alt="banner"
                          fill
                          priority
                        />
                      </div>
                      <div className={styles.metronzTitle}>Healthy Home Standards </div>
                  </div>
                </Grid>

                <Grid item xs={3}>
                  <div className={styles.metronzImgWrap}>
                    <div className={styles.metronzImg}>
                        <Image
                          src={insights3}
                          alt="banner"
                          fill
                          priority
                        />
                      </div>
                      <div className={styles.metronzTitle}>Healthy Home Standards </div>
                  </div>
                </Grid>

                <Grid item xs={3}>
                  <div className={styles.metronzImgWrap}>
                    <div className={styles.metronzImg}>
                        <Image
                          src={insights4}
                          alt="banner"
                          fill
                          priority
                        />
                      </div>
                      <div className={styles.metronzTitle}>Healthy Home Standards </div>
                  </div>
                </Grid>
            </Grid>
        </Box>
        <div className={styles.containers}>
        <Box sx={{ flexGrow: 1, mt: 4 }}>
            <Grid container spacing={4}>
                <Grid item xs={4}>
                  <div className={styles.feedback}>
                      <Image
                        src={feedback}
                        alt="banner"
                        fill
                        priority
                      />
                  </div>
                </Grid>
                <Grid item xs={8}>
                 
                  <div className={styles.feedbackTx}>
                      Everything was very smooth and efficient, which I really appreciated and i will be recommending them to others looking for home. 
                      <div className={styles.feedbackReadMore}><Link href="#">Read More...</Link></div>
                  </div>
                </Grid>
               
            </Grid>
          </Box>
          </div>
        <div className={styles.testimonial}>
        <Box sx={{ flexGrow: 1, mt: 4 }}>
            <Grid container spacing={3}>
                <Grid item xs={4}>
                <div className={styles.testimonialImgWrap}>
                  <div className={styles.testimonialImg}>
                      <Image
                        src={testimonial}
                        alt="banner"
                        fill
                        priority
                      />
                  </div>
                  </div>
                </Grid>
                <Grid item xs={8}>
                  <div className={styles.testimonialTxTop}>
                    Zsuzsanna Tantos-Rang <br/>
                    Managing Director / Senior Property Manager
                  </div>
                  <div className={styles.testimonialTxBottom}>
                  Goal-orientated, well directed, rational and approachable, Zsuzsanna Tantos-Rangi is a Managing Director of Metro NZ Euro Division, also a senior international property manager in NZ and with almost thirty years of entrepreneurial experience.

                  </div>
                  <div className={styles.feedbackReadMore}><Link href="#">Read More...</Link></div>
                </Grid>
               
            </Grid>
          </Box>
        </div>

        <Box sx={{ flexGrow: 1, mt: 4 }}>
            <Grid container spacing={8}>
                <Grid item xs={8}>
                  <div className={styles.contact}>
                    <p>Contact Details</p>
                    <h3>We are keen to work with you . Call our team in Auckland by phone is the best way to get in touch with us.</h3>
                    <div className={styles.divider}></div>
                    <p>Location</p>
                    <h3>Metro NZ Property Management Ltd 
                    Level 33, ANZ Center, 23-29, Albert Street, Auckland 1010,
                    New Zealand</h3>

                  </div>
                  <div className={`${styles.contact} ${styles.contactContent}`}>
                    <Grid container spacing={8}>
                      <Grid item xs={6}>
                        <p>Email</p>
                        <h3>info@metronz.co.nz</h3>
                      </Grid>
                      <Grid item xs={6}>
                        <p>Phone number</p>
                        <h3>093914642  | +6421642119</h3>
                      </Grid>
                      <Grid item xs={12}>
                        <div className={`${styles.socialIcon} ${styles.instagram}`}></div>
                        <div className={`${styles.socialIcon} ${styles.fb}`}></div>
                        <div className={`${styles.socialIcon} ${styles.twitter}`}></div>
                        <div className={`${styles.socialIcon} ${styles.linkdin}`}></div>
                      </Grid>
                    </Grid>
                  </div>
                </Grid>
                <Grid item xs={4}>
                 <div className={styles.getInTouch}>
                  <h3>Get In Touch</h3>
                    <div className={styles.label}>
                      <p>Your Name</p>
                        <TextField id="outlined-basic" label="Text" variant="outlined" fullWidth/>
                    </div>
                    <div className={styles.label}>
                      <p>Your Email</p>
                        <TextField id="outlined-basic" label="Text" variant="outlined" fullWidth/>
                    </div>
                    <div className={styles.label}>
                      <p>Subject</p>
                        <TextField id="outlined-basic" label="Text" variant="outlined" fullWidth/>
                    </div>
                    <div className={styles.label}>
                      <p>Your Message</p>
                        <TextField
                          id="outlined-multiline-static"
                          label="Text"
                          multiline
                          rows={4}
                          fullWidth
                        />
                    </div>
                 </div>
                </Grid>
               
            </Grid>
          </Box>

          <div className={styles.containers}>
          <Box sx={{ flexGrow: 1, mt: 4 }}>
            <Grid container spacing={8}>
                <Grid item xs={6}>
                  <div className={styles.award}>
                    <Grid item xs={12}><div className={styles.awardTitle}>Award</div></Grid>
                      <Grid container spacing={4}>
                        <Grid item xs={4}>
                          <div className={styles.awardImg}>
                            <Image
                              src={award1}
                              alt="banner"
                              layout="responsive"
                              priority
                            />
                          </div>
                        </Grid>
                        <Grid item xs={4}>
                        <div className={styles.awardImg}>
                            <Image
                              src={award2}
                              alt="banner"
                              layout="responsive"
                              priority
                            />
                          </div>
                        </Grid>
                        <Grid item xs={4}>
                          <div className={styles.awardImg}>
                            <Image
                              src={award3}
                              alt="banner"
                              layout="responsive"
                              priority
                            />
                          </div>
                        </Grid>
                      </Grid>
                   
                  </div>
                </Grid>
                <Grid item xs={6}>
                <div className={styles.award}>
                    <Grid item xs={12}><div className={styles.awardTitle}>Social Responsibility</div></Grid>
                      <Grid container spacing={4}>
                        <Grid item xs={4}>
                          <div className={styles.awardImg}>
                            <Image
                              src={award4}
                              alt="banner"
                              layout="responsive"
                              priority
                            />
                          </div>
                        </Grid>
                       
                      </Grid>
                   
                  </div>
                </Grid>
               
            </Grid>
          </Box>
          </div>
      </div> 
     <div className={styles.footer}>
      <Image
          src={footerBg}
          alt="banner"
          layout="responsive"
          priority
        />
     </div>
     
    </>
  )
}
